"""DATABRICKS CONFIDENTIAL & PROPRIETARY
__________________

Copyright 2025 Databricks, Inc.
All Rights Reserved.

NOTICE:  All information contained herein is, and remains the property of Databricks, Inc.
and its suppliers, if any. The intellectual and technical concepts contained herein are
proprietary to Databricks, Inc. and its suppliers and may be covered by U.S. and foreign patents,
patents in process, and are protected by trade secret and/or copyright law. Dissemination, use,
or reproduction of this information is strictly forbidden unless prior written permission is
obtained from Databricks, Inc.

If you view or obtain a copy of this information and believe Databricks, Inc. may not have
intended it to be made available, please promptly report it to Databricks Legal Department
at legal@databricks.com.
"""

# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: temporary_credential.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1atemporary_credential.proto\x12%com.databricks.spark.safespark.udf.pb\"\xe6\x01\n\x1aTemporaryCredentialRequest\x12\x17\n\x0f\x63redential_name\x18\x01 \x01(\t\x12J\n\tresources\x18\x02 \x01(\x0b\x32\x35.com.databricks.spark.safespark.udf.pb.AzureResourcesH\x00\x12\x42\n\x06scopes\x18\x03 \x01(\x0b\x32\x30.com.databricks.spark.safespark.udf.pb.GCPScopesH\x00\x12\x14\n\x0csandbox_uuid\x18\x04 \x01(\tB\t\n\x07options\" \n\x0e\x41zureResources\x12\x0e\n\x06values\x18\x01 \x03(\t\"\x1b\n\tGCPScopes\x12\x0e\n\x06values\x18\x01 \x03(\t\"o\n\x1bTemporaryCredentialResponse\x12P\n\x0b\x63redentials\x18\x01 \x02(\x0b\x32;.com.databricks.spark.safespark.udf.pb.TemporaryCredentials\"\xbd\x02\n\x14TemporaryCredentials\x12U\n\x14\x61ws_temp_credentials\x18\x02 \x01(\x0b\x32\x35.com.databricks.spark.safespark.udf.pb.AwsCredentialsH\x00\x12U\n\tazure_aad\x18\x03 \x01(\x0b\x32@.com.databricks.spark.safespark.udf.pb.AzureActiveDirectoryTokenH\x00\x12O\n\x0fgcp_oauth_token\x18\x04 \x01(\x0b\x32\x34.com.databricks.spark.safespark.udf.pb.GcpOauthTokenH\x00\x12\x17\n\x0f\x65xpiration_time\x18\x01 \x01(\x03\x42\r\n\x0b\x63redentials\"o\n\x0e\x41wsCredentials\x12\x15\n\raccess_key_id\x18\x01 \x01(\t\x12\x19\n\x11secret_access_key\x18\x02 \x01(\t\x12\x15\n\rsession_token\x18\x03 \x01(\t\x12\x14\n\x0c\x61\x63\x63\x65ss_point\x18\x04 \x01(\t\".\n\x19\x41zureActiveDirectoryToken\x12\x11\n\taad_token\x18\x01 \x01(\t\"$\n\rGcpOauthToken\x12\x13\n\x0boauth_token\x18\x01 \x01(\t2\xbe\x01\n#TemporaryCredentialRetrieverService\x12\x96\x01\n\rGetCredential\x12\x41.com.databricks.spark.safespark.udf.pb.TemporaryCredentialRequest\x1a\x42.com.databricks.spark.safespark.udf.pb.TemporaryCredentialResponse')



_TEMPORARYCREDENTIALREQUEST = DESCRIPTOR.message_types_by_name['TemporaryCredentialRequest']
_AZURERESOURCES = DESCRIPTOR.message_types_by_name['AzureResources']
_GCPSCOPES = DESCRIPTOR.message_types_by_name['GCPScopes']
_TEMPORARYCREDENTIALRESPONSE = DESCRIPTOR.message_types_by_name['TemporaryCredentialResponse']
_TEMPORARYCREDENTIALS = DESCRIPTOR.message_types_by_name['TemporaryCredentials']
_AWSCREDENTIALS = DESCRIPTOR.message_types_by_name['AwsCredentials']
_AZUREACTIVEDIRECTORYTOKEN = DESCRIPTOR.message_types_by_name['AzureActiveDirectoryToken']
_GCPOAUTHTOKEN = DESCRIPTOR.message_types_by_name['GcpOauthToken']
TemporaryCredentialRequest = _reflection.GeneratedProtocolMessageType('TemporaryCredentialRequest', (_message.Message,), {
  'DESCRIPTOR' : _TEMPORARYCREDENTIALREQUEST,
  '__module__' : 'temporary_credential_pb2'
  # @@protoc_insertion_point(class_scope:com.databricks.spark.safespark.udf.pb.TemporaryCredentialRequest)
  })
_sym_db.RegisterMessage(TemporaryCredentialRequest)

AzureResources = _reflection.GeneratedProtocolMessageType('AzureResources', (_message.Message,), {
  'DESCRIPTOR' : _AZURERESOURCES,
  '__module__' : 'temporary_credential_pb2'
  # @@protoc_insertion_point(class_scope:com.databricks.spark.safespark.udf.pb.AzureResources)
  })
_sym_db.RegisterMessage(AzureResources)

GCPScopes = _reflection.GeneratedProtocolMessageType('GCPScopes', (_message.Message,), {
  'DESCRIPTOR' : _GCPSCOPES,
  '__module__' : 'temporary_credential_pb2'
  # @@protoc_insertion_point(class_scope:com.databricks.spark.safespark.udf.pb.GCPScopes)
  })
_sym_db.RegisterMessage(GCPScopes)

TemporaryCredentialResponse = _reflection.GeneratedProtocolMessageType('TemporaryCredentialResponse', (_message.Message,), {
  'DESCRIPTOR' : _TEMPORARYCREDENTIALRESPONSE,
  '__module__' : 'temporary_credential_pb2'
  # @@protoc_insertion_point(class_scope:com.databricks.spark.safespark.udf.pb.TemporaryCredentialResponse)
  })
_sym_db.RegisterMessage(TemporaryCredentialResponse)

TemporaryCredentials = _reflection.GeneratedProtocolMessageType('TemporaryCredentials', (_message.Message,), {
  'DESCRIPTOR' : _TEMPORARYCREDENTIALS,
  '__module__' : 'temporary_credential_pb2'
  # @@protoc_insertion_point(class_scope:com.databricks.spark.safespark.udf.pb.TemporaryCredentials)
  })
_sym_db.RegisterMessage(TemporaryCredentials)

AwsCredentials = _reflection.GeneratedProtocolMessageType('AwsCredentials', (_message.Message,), {
  'DESCRIPTOR' : _AWSCREDENTIALS,
  '__module__' : 'temporary_credential_pb2'
  # @@protoc_insertion_point(class_scope:com.databricks.spark.safespark.udf.pb.AwsCredentials)
  })
_sym_db.RegisterMessage(AwsCredentials)

AzureActiveDirectoryToken = _reflection.GeneratedProtocolMessageType('AzureActiveDirectoryToken', (_message.Message,), {
  'DESCRIPTOR' : _AZUREACTIVEDIRECTORYTOKEN,
  '__module__' : 'temporary_credential_pb2'
  # @@protoc_insertion_point(class_scope:com.databricks.spark.safespark.udf.pb.AzureActiveDirectoryToken)
  })
_sym_db.RegisterMessage(AzureActiveDirectoryToken)

GcpOauthToken = _reflection.GeneratedProtocolMessageType('GcpOauthToken', (_message.Message,), {
  'DESCRIPTOR' : _GCPOAUTHTOKEN,
  '__module__' : 'temporary_credential_pb2'
  # @@protoc_insertion_point(class_scope:com.databricks.spark.safespark.udf.pb.GcpOauthToken)
  })
_sym_db.RegisterMessage(GcpOauthToken)

_TEMPORARYCREDENTIALRETRIEVERSERVICE = DESCRIPTOR.services_by_name['TemporaryCredentialRetrieverService']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TEMPORARYCREDENTIALREQUEST._serialized_start=70
  _TEMPORARYCREDENTIALREQUEST._serialized_end=300
  _AZURERESOURCES._serialized_start=302
  _AZURERESOURCES._serialized_end=334
  _GCPSCOPES._serialized_start=336
  _GCPSCOPES._serialized_end=363
  _TEMPORARYCREDENTIALRESPONSE._serialized_start=365
  _TEMPORARYCREDENTIALRESPONSE._serialized_end=476
  _TEMPORARYCREDENTIALS._serialized_start=479
  _TEMPORARYCREDENTIALS._serialized_end=796
  _AWSCREDENTIALS._serialized_start=798
  _AWSCREDENTIALS._serialized_end=909
  _AZUREACTIVEDIRECTORYTOKEN._serialized_start=911
  _AZUREACTIVEDIRECTORYTOKEN._serialized_end=957
  _GCPOAUTHTOKEN._serialized_start=959
  _GCPOAUTHTOKEN._serialized_end=995
  _TEMPORARYCREDENTIALRETRIEVERSERVICE._serialized_start=998
  _TEMPORARYCREDENTIALRETRIEVERSERVICE._serialized_end=1188
# @@protoc_insertion_point(module_scope)
